### ISSUE TITLE
Error: self signed certificate at TLSSocket.onConnectSecure

### ISSUE THREAD

**Issue by Petar-np** [andris9/imapapi#34]
**Describe the bug**
I'm not sure if this is a bug or not, but I can't connect anymore to the account I previously could connect. It says that there is some kind of problem with ssl, but at this point I'm not sure why. Only difference to what I was doing before is that I've changed my computer, I got new one.

**To Reproduce**
1. Run `npx imapapi --dbs.redis="redis://127.0.0.1:6379"`
2. Create account:
```
curl -XPOST "localhost:3000/v1/account" -H "content-type: application/json" -d '{
    "account": "example",
    "name": "My Example Account",
    "imap": {
        "host": "<your-address>",
        "port": 143,
        "secure": false,
        "auth": {
            "user": "<your-account>",
            "pass": "<account-password>"        
        }
    },
    "smtp": {
        "host": "<your-address>",
        "port": 587,
        "secure": false,
        "auth": {
            "user": "<your-account>",
            "pass": "<account-password>"        
        }
    }
}'
```
```
{"level":50,"time":1599900200040,"pid":35652,"hostname":"Petars-MacBook-Pro.local","tid":1,"component":"imap-client","account":"example","cid":"p5z2cthej55ac95qj3yw","sub":"imap-connection","err":{"type":"Error","message":"self signed certificate","stack":"Error: self signed certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:936:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)","code":"DEPTH_ZERO_SELF_SIGNED_CERT"},"cid":"1b2ngnrkkokz1ejy9wzf"}
{"level":50,"time":1599900200041,"pid":35652,"hostname":"Petars-MacBook-Pro.local","tid":1,"component":"imap-client","account":"example","cid":"p5z2cthej55ac95qj3yw","msg":"IMAP connection error","account":"example","err":{"type":"Error","message":"self signed certificate","stack":"Error: self signed certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:936:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)","code":"DEPTH_ZERO_SELF_SIGNED_CERT"}}
{"level":50,"time":1599900200041,"pid":35652,"hostname":"Petars-MacBook-Pro.local","tid":1,"component":"imap-client","account":"example","cid":"p5z2cthej55ac95qj3yw","msg":"Failed to connect","account":"example","err":{"type":"Error","message":"Unexpected close","stack":"Error: Unexpected close\n    at ImapFlow.close (/Users/developera/.npm/_npx/35652/lib/node_modules/imapapi/node_modules/imapflow/lib/imap-flow.js:1116:20)\n    at Immediate.<anonymous> (/Users/developera/.npm/_npx/35652/lib/node_modules/imapapi/node_modules/imapflow/lib/imap-flow.js:490:41)\n    at processImmediate (internal/timers.js:456:21)"}}
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6

**Adittional context
Username and password are correct, I can log in into mailbox. IMAP and SMTP ports are also correct, I've tested connection with `telnet`

**Comment by Petar-np** [comment]
Resolved by adding option:
```
"tls": {
            "rejectUnauthorized": false
        }
```
so the final request looks like this:
```
curl -XPOST "localhost:3000/v1/account" -H "content-type: application/json" -d '{
    "account": "example",
    "name": "My Example Account",
    "imap": {
        "host": "<your-address>",
        "port": 143,
        "secure": false,
        "auth": {
            "user": "<your-account>",
            "pass": "<account-password>"        
        },
       "tls": {
            "rejectUnauthorized": false
        }
    },
    "smtp": {
        "host": "<your-address>",
        "port": 587,
        "secure": false,
        "auth": {
            "user": "<your-account>",
            "pass": "<account-password>"        
        },
       "tls": {
            "rejectUnauthorized": false
        }
    }
}'
```
Interesting thing is that it still doesn't work if I try to connect using user interface, even with unchecked `use TLS` option
