### ISSUE TITLE
Internar Server Error - get text of message

### ISSUE THREAD

**Issue by wciurzynski** [andris9/imapapi#54]
Version 1.4.6

When I try to get text for message where there is no text nor html I get Internal Server.
In raw message there is:
**some headers**
Content-Type: text/plain; charset=utf-8
Content-Disposition: inline
User-Agent: Mutt/1.5.23 (2014-03-12)
**some headers**

In normal email where sb write something after text/plain there is some text. In this problematic email there is no text nor html.
I think IMAPAPI should return null or empty string.

"err":{"type":"IncompleteBufferError","message":"unable to decode","stack":"IncompleteBufferError: unable to decode\n    at Object.decode (/usr/local/conpeek/apis/imapapi/node_modules/msgpack5/lib/decoder.js:51:24)\n    at Connection.getMessageTextPaths (/usr/local/conpeek/apis/imapapi/lib/connection.js:191:33)\n    at Connection.getText (/usr/local/conpeek/apis/imapapi/lib/connection.js:737:49)\n    at ConnectionHandler.getText (/usr/local/conpeek/apis/imapapi/workers/imap.js:167:45)\n    at ConnectionHandler.onCommand (/usr/local/conpeek/apis/imapapi/workers/imap.js:441:35)\n    at MessagePort.<anonymous> (/usr/local/conpeek/apis/imapapi/workers/imap.js:561:14)\n    at MessagePort.emit (events.js:315:20)\n    at MessagePort.onmessage (internal/worker/io.js:78:8)\n    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)","name":"IncompleteBufferError"}}

**Comment by wciurzynski** [comment]
There was no error - I sent to API bad ID
